# Generated by Django 3.0.4 on 2020-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.shareicon.net/data/512x512/2016/08/04/806801_pin_512x512.png', max_length=500),
        ),
    ]
